"use strict";var _typeof=typeof Symbol==="function"&&typeof Symbol.iterator==="symbol"?function(obj){return typeof obj}:function(obj){return obj&&typeof Symbol==="function"&&obj.constructor===Symbol&&obj!==Symbol.prototype?"symbol":typeof obj};var _createClass=function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor)}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor}}();function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function")}}var Textbox=function(){function Textbox(){_classCallCheck(this,Textbox);this.currentName="none";this.centered=false;this.animating=false;this.italic=false;this.bold=false;this.nfontsize="1.5vw";this.cfontsize="2.5vw";this.color="black";this.cLoop=null;this.speed=1;this.textDelay=textSpeed;this.skippable=true;this.count=0;//
this.end=null}//setters
_createClass(Textbox,[{key:"setName",value:function setName(name){this.currentName=name}},{key:"setCenter",value:function setCenter(center){this.centered=center}},{key:"setUnskippable",value:function setUnskippable(){this.skippable=false}},{key:"setSize",value:function setSize(size){if(this.centered){this.cfontsize=size}else{this.nfontsize=size}}},{key:"setColor",value:function setColor(color){this.color=color}},{key:"setBold",value:function setBold(bold){this.bold=bold}},{key:"setItalic",value:function setItalic(i){this.italic=i}},{key:"removeName",value:function removeName(){this.currentName="none"}//getters
},{key:"isAnimating",value:function isAnimating(){return this.animating}},{key:"isSkippable",value:function isSkippable(){return this.skippable}},{key:"getCurrentText",value:function getCurrentText(){return this.currentText}//Methods, Abilites
},{key:"closeTextBox",value:function closeTextBox(promise){$("#maintext").css("display","none");$("#centered").css("display","none");$("#top-left").css("display","none");$("#nametext").css("display","none").promise().done(function(){if(promise!==null&&typeof promise!=="undefined"){if(typeof promise==="function"){promise()}else{displayError("Promise exception: promise isn't a function! <br> PromiseType : "+(typeof promise==="undefined"?"undefined":_typeof(promise))+"<br> Promise: "+promise)}}});this.currentText="nulldefaulttext"}},{key:"kill",value:function kill(){clearInterval(this.cLoop)}},{key:"pause",value:function pause(){if(this.isAnimating()){var c="#centered span";var t="#top-left span";var animations=TweenLite.getTweensOf([c,t]);for(var i=0;i<animations.length;i++){animations[i].pause()}}}},{key:"resume",value:function resume(){var c="#centered span";var t="#top-left span";var animations=TweenLite.getTweensOf([c,t]);for(var i=0;i<animations.length;i++){if(animations[i].paused()){animations[i].play()}}}},{key:"displayfinish",value:function displayfinish(force){var ele=this;if(ele.animating){if(ele.skippable||force){if(this.cLoop===null||typeof this.cLoop==="undefined"){var c="#centered span";var t="#top-left span";var animations=TweenLite.getTweensOf([c,t]);for(var i=0;i<animations.length;i++){animations[i].progress(1)}}else{this.end()}return this.displayfinish(force)}else{return false}}else{return true}}},{key:"getFontSize",value:function getFontSize(){var cfs=this.cfontsize;var cfsv=parseFloat(cfs.match(/^(\d+(?:\.\d+)?)(.*)$/)[1]);var cfsu=cfs.match(/^(\d+(?:\.\d+)?)(.*)$/)[2];var cfsf=cfsv*window.kvnCurrentRatio+cfsu;var nfs=this.nfontsize;var nfsv=parseFloat(nfs.match(/^(\d+(?:\.\d+)?)(.*)$/)[1]);var nfsu=nfs.match(/^(\d+(?:\.\d+)?)(.*)$/)[2];var nfsf=nfsv*window.kvnCurrentRatio+nfsu;return this.centered?cfsf:nfsf}},{key:"getOFontSize",value:function getOFontSize(){return this.centered?this.cfontsize:this.nfontsize}},{key:"fadeInText",value:function fadeInText(text,promise,time,clear){if(!this.animating){//increment
this.count++;//mark current text
if(clear){$("#centered").html("");$("#top-left #actual-text").html("");this.count=0}//cleani nput
time=this.sanitizeInput("number",time,1000,"time","displayText in text engine");clear=this.sanitizeInput("boolean",clear,true,"clear","displayText in text engine");text=this.sanitizeInput("string",text,"If you see this text, you probably fucked up! :> - Kirinnee","displayText in text engine");this.animating=true;//scope pointer
var tb=this;var name=this.currentName;var center=this.centered;//displays name
var showName=this.currentName!=="none";//adjust box
$("#name-text").html(showName?name:"");tb.toggleToCorrect($("#nametext"),showName);//flag for centering
var dEle=center?$("#centered"):$("#top-left #actual-text");//obtain fontsize
var fs=tb.getFontSize();var fso=tb.getOFontSize();//toggle transparency properly
tb.toggleToCorrect($("#maintext"),true);tb.toggleToCorrect($("#centered"),center);tb.toggleToCorrect($("#top-left"),!center);//unique
var uid="kvn-text-engine-id-"+this.count;var cls=(this.italic?"italic ":"")+(this.bold?"bold":"");//add the newest element in!
console.log(fs());dEle.append("<span class='knv-th-ele "+cls+"' id='"+uid+"' style='font-size:"+tb.getFontSize()+";color:"+this.color+";opacity:0;' ofs='"+tb.getOFontSize()+"'>"+this.parseHTMLString(text)+"</span>");TweenLite.to($("#"+uid),time/1000,{opacity:1,immediateRender:true,onComplete:function onComplete(){tb.animating=false;tb.skippable=true;if(typeof promise==="function"){promise()}}});return true}else{return false}}},{key:"displayText",value:function displayText(text,promise,time,clear,nl,appendSpace){if(!this.animating){//clean input
time=this.sanitizeInput("number",time,null,"time","displayText in text engine",true);clear=this.sanitizeInput("boolean",clear,true,"clear","displayText in text engine");text=this.sanitizeInput("string",text,"Null is not an accepted argument for speaking - Kirinnee","displayText in text engine");nl=this.sanitizeInput("boolean",nl,false,"displayText in text engine");appendSpace=this.sanitizeInput("boolean",appendSpace,true,"displayText in text engine");//increment
this.count++;//mark current text
if(clear){$("#centered").html("");$("#top-left #actual-text").html("");this.count=0}//interval
var interval=this.speed*20/this.textDelay;//console.log(interval)
//time setting
if(time!==null&&typeof time!=="undefined"){interval=Math.ceil(time/text.length)}//console.log(interval);
//flag
this.animating=true;//loop counter
var c=0;//scope pointer
var tb=this;var name=this.currentName;var center=this.centered;//displays name
var showName=this.currentName!=="none";//adjust box
$("#name-text").html(showName?name:"");tb.toggleToCorrect($("#nametext"),showName);//flag for centering
var dEle=center?$("#centered"):$("#top-left #actual-text");//obtain fontsize
//toggle transparency properly
tb.toggleToCorrect($("#maintext"),true);tb.toggleToCorrect($("#centered"),center);tb.toggleToCorrect($("#top-left"),!center);//looping mech
var c=0;//unique
var uid="kvn-text-engine-id-"+this.count;var cls=(this.italic?"italic ":"")+(this.bold?"bold":"");//add the newest element in!
dEle.append("<span class='knv-th-ele "+cls+"' id='"+uid+"' style='font-size:"+tb.getFontSize()+";color:"+this.color+";' ofs='"+tb.getOFontSize()+"'></span>");$("#"+uid).append(this.formatForReveal(text,clear,nl,appendSpace));this.end=function(){clearInterval(tb.cLoop);tb.cLoop=null;$("#"+uid+" .engine-char").addClass("vis").promise().done(function(){tb.skippable=true;tb.animating=false;tb.end=null;if(typeof promise==="function"){promise()}})};this.cLoop=setInterval(function(){if(!pause){if(c===text.length-1){tb.end()}else{$("#"+uid+" .word .engine-char").eq(c).addClass("vis");c++}}},interval);return true}else{return false}}},{key:"formatForReveal",value:function formatForReveal(string,clear,nl,append){if(!clear&&append)string=" "+string;var ret="<span class='word'>";for(var i=0;i<string.length;i++){var char=string.charAt(i);if(char===" "){ret+="</span><span class='word'><span clas='engine-char'>&nbsp;</span></span><span class='word'>"}else{ret+="<span class='engine-char'>"+this.parseHTML(char)+"</span>"}}ret+"</span>";if(nl)ret="<br>"+ret;return ret}},{key:"parseHTMLString",value:function parseHTMLString(string){return string.replace(">","&lt;").replace("<","&gt;").replace("&","&amp;").replace("\"","&quot;").replace("'","&apos;").replace(" ","&nbsp;")}},{key:"parseHTML",value:function parseHTML(character){if(character==="<"){return"&lt;"}if(character===">"){return"&gt;"}if(character==="&"){return"&amp;"}if(character==="\""){return"&quot;"}if(character==="'"){return"&apos;"}if(character===" "){return"&nbsp;"}return character}},{key:"toggleToCorrect",value:function toggleToCorrect(selector,display){var sD=selector.css("display")==="block";if(display!==sD){var nD=display?"block":"none";selector.css("display",nD)}}},{key:"throwError",value:function throwError(errorMessage){displayError(errorMessage+"<br> At text engine"+"<br> Scene: "+getCurrentSceneID()+"<br> Frame: "+getCurrentFrame())}},{key:"sanitizeInput",value:function sanitizeInput(acceptedType,input,cdef,paramName,methodName,acceptNull){if(input===null||typeof input==="undefined"){input=cdef}if(input===def){input=cdef}var shortcur=true;if(acceptNull===true){if(input===null){shortcur=false}}if((typeof input==="undefined"?"undefined":_typeof(input))!==acceptedType&&shortcur){displayError("Type Exception: '"+paramName+"' parameter in method '"+methodName+"' must be a "+acceptedType+"! "+"<br>"+paramName+" input type: "+(typeof input==="undefined"?"undefined":_typeof(input))+"<br>"+paramName+" input value: "+input+"<br> Scene: "+getCurrentSceneID()+"<br> Frame: "+getCurrentFrame())}return input}}]);return Textbox}();